Feat/workflow quickstart
diagridio/catalyst-quickstarts pull request #21
Opened 2024-06-28 20:03 UTC by Eileen-Yu

part of the effort to resolve https://github.com/diagridio/issues/issues/4232

first need to copy the [existing workflow sample code](https://github.com/diagridio/catalyst-samples/pull/37) to this quickstart repo

2024-07-02 01:39 UTC, Eileen-Yu commented
<img width="1378"  src="https://github.com/diagridio/catalyst-quickstarts/assets/48944635/676705a9-6886-491b-b75f-8f31b2befa77">

2024-07-02 17:06 UTC, Eileen-Yu commented
<img width="1592"  src="https://github.com/diagridio/catalyst-quickstarts/assets/48944635/81d640ed-0eb0-4207-bca4-debac444b965">

2024-07-03 10:16 UTC, alicejgibbons commented on workflow/csharp/Program.cs
> +// Get completed workflow output
Should we also add methods for terminating, pausing and resuming the workflow? I know i didnt in my PR but think this would be good to add for the official quickstart: https://docs.dapr.io/reference/api/workflow_api/#terminate-workflow-request

2024-07-03 10:21 UTC, alicejgibbons commented on workflow/csharp/Activities/NotifyActicity.cs
> +    public class NotifyActivity : WorkflowActivity<Notification, object>
Spelling mistake in the file name

2024-07-03 10:35 UTC, alicejgibbons requested changes

2024-07-03 10:35 UTC, alicejgibbons commented on workflow/csharp/Program.cs
> +        app.Logger.LogInformation("STATE: {state}", state.ToString());
![image](https://github.com/diagridio/catalyst-quickstarts/assets/14792988/f35b1567-d463-442d-b4b7-0dc4e3e776e2)

Can probably delete this line since its just printing the object. Maybe standardize this output on line 64 to make it consistent with with get workflow output?

2024-07-03 10:35 UTC, alicejgibbons commented on workflow/csharp/Program.cs
> +            app.Logger.LogInformation("Get Workflow status successful. Workflow Runtime Status is: {status} ", state.RuntimeStatus);
Standardize, ie:
```csharp
app.Logger.LogInformation("Retrieved workflow status for {id}.", id);
app.Logger.LogInformation("Workflow Runtime Status is: {status} ", state.RuntimeStatus);
```

2024-07-03 10:35 UTC, alicejgibbons commented on workflow/csharp/Program.cs
> +            app.Logger.LogInformation("Output: {output}", output);
For standardization we can make this one like 
```suggestion
            app.Logger.LogInformation("Workflow output is: {output} ", output);
```

2024-07-03 10:35 UTC, alicejgibbons commented on workflow/csharp/Program.cs
> +            app.Logger.LogInformation("Get Workflow status successful. Workflow Runtime Status is: {status} ", state.RuntimeStatus);
or make it one log message but make sure its the same across all methods.

2024-07-04 03:24 UTC, Eileen-Yu commented on workflow/csharp/Program.cs
> +var client = new DaprClientBuilder().Build();
should drop, nice catch!

2024-07-04 03:24 UTC, Eileen-Yu commented on workflow/csharp/OrderProcessingWorkflow.cs
> +                    new Notification($"Insufficient inventory for {order.Name}"));
sure, updated!

2024-07-04 03:24 UTC, Eileen-Yu commented on workflow/csharp/Program.cs
> +// Get completed workflow output
updated 🚀

2024-07-04 03:26 UTC, Eileen-Yu commented
thx @alicejgibbons ! it's readyyyyy

<img width="854" src="https://github.com/diagridio/catalyst-quickstarts/assets/48944635/62ad7474-a058-470b-8180-00335833770d">

<img width="822"  src="https://github.com/diagridio/catalyst-quickstarts/assets/48944635/1dfa68bc-1eca-4bd9-a9d5-2c9605dbafc8">

2024-07-05 09:57 UTC, alicejgibbons approved these changes
Looks great! just couple println standardizations but otherwise g2g

2024-07-05 09:57 UTC, alicejgibbons commented on workflow/csharp/Program.cs
> +            app.Logger.LogInformation("Workflow Runtime Status is: {status} ", state.RuntimeStatus);
Can remove this line.

2024-07-05 09:57 UTC, alicejgibbons commented on workflow/csharp/Program.cs
> +            app.Logger.LogInformation("Workflow Runtime Status is: {status} ", state.RuntimeStatus);
Can remove this line.

2024-07-05 09:57 UTC, alicejgibbons commented on workflow/csharp/Program.cs
> +            app.Logger.LogInformation("Workflow Runtime Status is: {status} ", state.RuntimeStatus);
Can remove this line.

2024-07-05 21:44 UTC, Eileen-Yu commented on workflow/csharp/Program.cs
> +            app.Logger.LogInformation("Retrieved workflow status for {id}.", id);
gotcha, update. I'll merge it on Monday if everything looks good

2024-07-08 11:59 UTC, alicejgibbons approved these changes

2024-07-08 15:02 UTC, merged