[wip] feat: add java sample code
diagridio/catalyst-quickstarts pull request #30
Opened 2024-07-16 00:09 UTC by Eileen-Yu

2024-07-17 01:06 UTC, Eileen-Yu reviewed
start workflow can work fine now, next step:
1. support get status, terminate, pause, resume
2. support container

2024-07-17 23:21 UTC, Eileen-Yu commented on workflow/java/src/main/java/io/dapr/quickstarts/workflows/WorkflowConfig.java
> +  @Bean
this to setup runtime only once during initialization

2024-07-18 21:37 UTC, Eileen-Yu commented on workflow/csharp/scaffold.py
> +        app['env']['ASPNETCORE_URLS'] = 'http://0.0.0.0:5001'
fix the host binding in container

2024-07-19 09:33 UTC, detzgk commented
Running it without -c produces an error: run.py expects arguments that aren't sent by the CLI:

```
> dg project quickstart --type workflow --language java
○  Checking application dependency for python...
python language dependency is installed.
○  Downloading sample application code from https://github.com/diagridio/catalyst-quickstarts...
○  workflow-java-project already exists, skipping download.
○  Creating project resources and scaffolding dev config...
Error happened when run quickstart: exit status 2
Output: 
Error Output: ['run.py']usage: run.py [-h] --project-name PROJECT_NAME --config-file CONFIG_FILE
              [--is-container]
run.py: error: the following arguments are required: --project-name, --config-file

Exit status 2```

2024-07-19 09:54 UTC, detzgk commented on workflow/java/entrypoint.sh
> +mvn clean install
If we move (or copy) this to the Dockerfile, we can make the image startup much faster, in case people end up having to docker run more than once, since the cached dependencies will get written to the docker image.

2024-07-19 13:46 UTC, sicoyle commented on workflow/java/pom.xml
> +      <artifactId>dapr-sdk-workflows</artifactId>
should we tweak the naming here? Is this from a dapr sdk sample upstream?

2024-07-19 18:24 UTC, Eileen-Yu commented on workflow/java/pom.xml
> +      <artifactId>dapr-sdk-workflows</artifactId>
i think it's thespecific pkg(artifact) name that is published in the Maven repository, which cannot be changed here

2024-07-19 19:58 UTC, Eileen-Yu commented on workflow/java/entrypoint.sh
> +mvn clean install
ohh great knowledge to know! Thx updated 🚀

2024-07-19 20:01 UTC, Eileen-Yu commented
> Running it without -c produces an error: run.py expects arguments that aren't sent by the CLI:
> 
> ```
> > dg project quickstart --type workflow --language java
> ○  Checking application dependency for python...
> python language dependency is installed.
> ○  Downloading sample application code from https://github.com/diagridio/catalyst-quickstarts...
> ○  workflow-java-project already exists, skipping download.
> ○  Creating project resources and scaffolding dev config...
> Error happened when run quickstart: exit status 2
> Output: 
> Error Output: ['run.py']usage: run.py [-h] --project-name PROJECT_NAME --config-file CONFIG_FILE
>               [--is-container]
> run.py: error: the following arguments are required: --project-name, --config-file
> 
> Exit status 2```
> ```

thx for catching this! updated, now it should works fine for both host and container 👍

2024-07-23 21:20 UTC, detzgk requested changes

2024-07-23 21:20 UTC, detzgk commented on workflow/java/src/main/java/io/dapr/quickstarts/workflows/activities/UpdateInventoryActivity.java
> +  private static final Logger logger = LoggerFactory.getLogger(NotifyActivity.class);
```suggestion
  private static final Logger logger = LoggerFactory.getLogger(UpdateInventoryActivity.class);
```

2024-07-23 21:20 UTC, detzgk commented on workflow/java/src/main/java/io/dapr/quickstarts/workflows/WorkflowApp.java
> +    logger.info(String.format("Received request to start workflow for item: %s with quantity: %d", order.getItemName(),
It's considered good form to use the logging library's built-in formatting:

```suggestion
    logger.info("Received request to start workflow for item: {} with quantity: {}", order.getItemName(),
```

That way log lines that won't be output (DEBUG lines in an INFO context) don't need to be formatted, which can be costly. (Every other log line is correct)

2024-07-23 22:00 UTC, Eileen-Yu commented on workflow/java/src/main/java/io/dapr/quickstarts/workflows/WorkflowApp.java
> +    logger.info(String.format("Received request to start workflow for item: %s with quantity: %d", order.getItemName(),
great to know thx!

2024-07-23 22:00 UTC, Eileen-Yu reviewed
readyyyyy 🚀

2024-07-24 08:23 UTC, detzgk approved these changes

2024-07-24 16:19 UTC, merged