csharp updates
diagridio/catalyst-quickstarts pull request #43
Opened 2024-08-29 01:04 UTC by kendallroden

Updates for all csharp quickstarts: 
- Update the run.py file to write with spinner.write vs print to avoid print conflicts 
- Remove unnecessary/redundant errors 
- Make dependency checks more streamlined
- Add timer to app id status check command to avoid reprints of the same message + actionable message on failure 
- Update spinner behavior to update the action with a success or failure and only print out additional information if context/error needed to be displayed 
- Remove output related to venv due to lack of benefit to user / clarity on what is happening (we can add this as a disclaimer in docs or put a one liner to describe why we are doing that to update the dev config) 

Update for invocation specifically: 
- Remove invocation prefixing on rest APIs as no longer needed with move to single api projects
- Remove caller target and request reply references to standardize on client server as requested by yaron 
- Update dev config to align to respective app id name changes 

Update for state specifically: 
- Remove invocation prefixing on rest APIs as no longer needed with move to single api projects
- Remove caller target and request reply references to standardize on client server app id language as requested by yaron

Update for workflow: 
- Update the app id name to be order-wf to reflect more context of the business scenario vs generic workflow-app

Areas with additional help needed: 
- I don't understand the case where an existing dev config with the same name would be present? Can someone help me understand the scenario here?

2024-08-29 15:35 UTC, Eileen-Yu reviewed
just double check with the file renaming like `...csharp/reply/appsettings.Development.json → ...sharp/client/appsettings.Development.json`

should it be request-->client, reply-->server ?

2024-08-29 15:39 UTC, Eileen-Yu commented on invocation/java/client/pom.xml
> +  <artifactId>client</artifactId>
also for here, should it be `server`? As I see below caller(request) -> client, target(reply)->server

2024-08-29 15:42 UTC, Eileen-Yu commented on invocation/javascript/dev-js-invoke-1.yaml
> +project: js-invoke-1
Do we need this scaffolded dev config file?? As user download the run.py it would generate a new one for user so we can remove it IMO.

2024-08-29 15:43 UTC, Eileen-Yu commented on invocation/javascript/run.py
> +NODEJS_INSTRUCTIONS = """ Node.js and npm must be installed for quickstart: https://nodejs.org/en/download """
If you hope i do the language check in CLI side before cloning these code, probably can remove these instructions and check function

2024-08-29 15:55 UTC, Eileen-Yu commented on pubsub/csharp/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
typo

2024-08-29 15:57 UTC, Eileen-Yu commented on pubsub/python/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
typo. also plsss check the other places if you copy & paste this line

2024-08-29 15:59 UTC, Eileen-Yu commented on workflow/python/scaffold.py
> +    if app['appId'] == 'order-wf':
would it be better to use complete name like `order-workflow` to make it clearer for user?

2024-08-29 16:02 UTC, Eileen-Yu commented on invocation/java/client/pom.xml
> +  <artifactId>client</artifactId>
if so, pls also double check other `invocation/..` places

2024-08-30 16:10 UTC, kendallroden commented on invocation/javascript/run.py
> +NODEJS_INSTRUCTIONS = """ Node.js and npm must be installed for quickstart: https://nodejs.org/en/download """
no it was just from all the tests. will remove

2024-08-30 16:10 UTC, kendallroden commented on invocation/javascript/test.rest
> +POST http://localhost:5001/order
the docs have the test.rest instructions in it and always did

2024-08-30 16:12 UTC, kendallroden commented on invocation/javascript/dev-js-invoke-1.yaml
> +project: js-invoke-1
already had local fix just hadnt pushed

2024-08-30 16:13 UTC, kendallroden commented on invocation/javascript/run.py
> +NODEJS_INSTRUCTIONS = """ Node.js and npm must be installed for quickstart: https://nodejs.org/en/download """
lets test your changed experience first before removing

2024-08-30 16:16 UTC, kendallroden commented on invocation/javascript/run.py
> +NODEJS_INSTRUCTIONS = """ Node.js and npm must be installed for quickstart: https://nodejs.org/en/download """
lets keep the script as is and comment out when we can test with an edge build

2024-08-30 16:18 UTC, kendallroden commented on pubsub/csharp/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
fixed

2024-08-30 16:18 UTC, kendallroden commented on pubsub/python/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
all good

2024-08-30 16:22 UTC, kendallroden commented on invocation/javascript/run.py
> +NODEJS_INSTRUCTIONS = """ Node.js and npm must be installed for quickstart: https://nodejs.org/en/download """
i think the nice thing about this is the script could technically run independently from the CLI so we need to assess the trade offs of each experience. happy to meet about this if you want to set up time to chat

2024-09-03 07:01 UTC, jjcollinge commented
Is this aligned with https://github.com/diagridio/cli/pull/558 - if so I suggest we merge and iterate

2024-09-03 14:01 UTC, kendallroden commented
yes lets merge plz

2024-09-03 14:20 UTC, jjcollinge commented
> just double check with the file renaming like `...csharp/reply/appsettings.Development.json → ...sharp/client/appsettings.Development.json`
> 
> should it be request-->client, reply-->server ?

I think this is a git diff issue where its showing the wrong mapping. The source looks ok.

2024-09-03 15:28 UTC, Eileen-Yu commented on invocation/csharp/run.py
>  def check_dotnet_installed():
can we comment out these language check for now, as I've done them on the CLI side, to avoid user downloading the sample code before the pre-req check fails

2024-09-03 15:29 UTC, Eileen-Yu commented on invocation/csharp/run.py
>      check_dotnet_installed()
also here, and for every type/language 🙏

2024-09-03 15:31 UTC, Eileen-Yu commented on pubsub/java/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
typo

2024-09-03 15:35 UTC, Eileen-Yu commented on invocation/csharp/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
typo

2024-09-03 15:35 UTC, Eileen-Yu commented on invocation/java/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
typo

2024-09-03 15:36 UTC, Eileen-Yu commented on invocation/javascript/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
typo

2024-09-03 15:36 UTC, Eileen-Yu commented on invocation/python/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
typo

2024-09-03 15:36 UTC, Eileen-Yu commented on pubsub/java/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
typo

2024-09-03 15:36 UTC, Eileen-Yu commented on pubsub/javascript/run.py
> +            run_command(f"rm -rf {eßnv_name}", check=True)
typo

2024-09-03 15:38 UTC, Eileen-Yu requested changes
awesome work, thank you soooo much @kendallroden !! Left several comments, let's update them then we are g2g 🚀

2024-09-03 17:14 UTC, Eileen-Yu commented on invocation/csharp/run.py
>  def check_dotnet_installed():
chatted with Joni, we can leave the language check here. I just noticed we currently don't have the check for python (all other languages are good). Could you pls add the logic to check for python 3.11+ ? Basically just in the same format as how we do the check for other languages.

2024-09-03 20:13 UTC, kendallroden commented on invocation/csharp/run.py
>  def check_dotnet_installed():
sounds good

2024-09-03 21:40 UTC, Eileen-Yu commented on README.md
>  ## Catalyst Quickstarts
thankuuuu!

2024-09-03 21:44 UTC, Eileen-Yu commented on invocation/python/run.py
let's add python dep check here, also for every type

2024-09-03 23:07 UTC, Eileen-Yu submitted a review, later dismissed
great work, pls check these items:
- rename directory `keyvalue/` to `state/` , as we discussed here: https://github.com/diagridio/cli/pull/558#discussion_r1737918473
- add python dep check for python 3.11+ for all types
- keep `check=True` for all languages as CLI need that to catch the dep check failure

2024-09-03 23:56 UTC, kendallroden commented on invocation/python/run.py
done

2024-09-04 14:47 UTC, jjcollinge approved these changes

2024-09-04 15:07 UTC, merged